<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), 'Directory.Build.props'))/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.props" />
  <PropertyGroup>
    <TargetFramework>$(StrideEditorTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UIFramework>Avalonia</UIFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>

  <!-- WPF Interop -->
  <ItemGroup Condition="'$(UIFramework)' == 'Wpf' Or '$(UIFramework)' == ''">
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  </ItemGroup>

  <!-- Avalonia Interop -->
  <ItemGroup Condition="'$(UIFramework)' == 'Avalonia'">
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stride.Core.Presentation\Stride.Core.Presentation.csproj" />
  </ItemGroup>

  <Import Project="$(StrideRoot)sources/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.targets" />
</Project>
